### ISSUE TITLE
Center doesn't work properly

### ISSUE THREAD

**Issue by dpfaffenbauer** [lorenzo/pinky#6] opened 2018-09-07 09:15 UTC
Without finding a fix or further investigating the issue, it seems that center doesn't work as it should. here is my layout:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width"/>
</head>
    <body>
            <table class="body">
                <tr>
                    <td class="center" align="center" valign="top">
                        <center>
                            <div>
                                <container class="body-drip">
                                    <spacer size="16"></spacer>

                                    <div>
<!-- this doesn't work -->
                                        <center>
                                            <img src="path to image"/>
                                        </center>
                                    </div>
                                </container>
                            </div>
                        </center>
                    </td>
                </tr>
            </table>
            <!-- prevent Gmail on iOS font size manipulation -->
            <div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
        </body>
</html>
```

this does work:

```html
<div class="center" align="center">
    <img src="path to image"/>
</div>
```

**Comment by lorenzo** [comment] 2018-09-07 09:35
Duplicate of #4

**Closed by lorenzo** 2018-09-07 09:35 UTC
